# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

    terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "2.55.0"
    }
  }
}

provider "azurerm" {
  # Configuration options
  features {
    
  }
}
