# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.55.0"
    }
  }
}

provider "azurerm" {
  # Configuration options
  features {

  }
}


data "azurerm_virtual_network" "imported_VNET" {
  count = var.existing_vnet != "" ? 1 : 0
  name = var.existing_vnet
  resource_group_name = var.existing_resource_group
}